sudo:  required

language: bash

services:
  - docker

script:
  - travis_wait 90 docker build -t joeydumont/archlinux-n64 .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master